#!/usr/bin/env bash
# Usage: jiff keychain-install

source stdlib

main () {
  exit_if_is_on_path "keychain"
  install_package "keychain"
  grep -q keychain .bashrc || update_bashrc
}

update_bashrc () {
  cat <<EOM >> .bashrc

/usr/bin/keychain --quiet "\${HOME}/.ssh/id_rsa"
source "\${HOME}/.keychain/\$(hostname)-sh"
EOM
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${HOME}" "main" "${@}"
