#!/usr/bin/env bash
# Usage: jiff vim-config
# Summary: Configure vim

source stdlib
source distrolib

main () {
  is_not_file "vimrc.local" || exit 0
  jiff slash-git
  curl -sL "https://raw.githubusercontent.com/binaryphile/five-minutes-of-vim/master/vimrc" | sudo tee vimrc.local >/dev/null
  git add --force vimrc.local
  git commit --message "add local vimrc"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "/etc/vim" "main" "${@}"
