#!/usr/bin/env bash

readonly install_dir=/opt/app/avwobt4
readonly repo_uri=bertrand:tmp
readonly git_version=2.7.4
readonly git_dir=git-$git_version
readonly git_filename=$git_dir-static-avwob.tar.gz

main() {
  [[ -d $install_dir ]] && exit
  export PATH=$PATH:$install_dir/bin
  which git >/dev/null 2>&1 || install_git
  install_basher
  install_jiff
  success_message
}

install_basher() {
  push_dir $install_dir
  git clone git@github.com:binaryphile/basher
  rm -rf basher/.git
  cp -r basher/* .
  rm -rf basher
  pop_dir
}

install_git () {
  cd "${install_dir}"
  scp "${repo_uri}/${git_filename}" .
  tar xzf "${git_filename}"
  rm "${git_filename}"
}

install_jiff() {
  export BASHER_ROOT=$install_dir
  "$install_dir"/bin/basher install binaryphile/jiff-personal
}

pop_dir() { popd >/dev/null ;}

push_dir() { pushd "$1" >/dev/null ;}

success_message() {
  cat <<EOM

Note: jiff is not installed for your shell yet.

You'll want to run:

$install_dir/bin/jiff role user
$install_dir/bin/jiff set context avwob
$install_dir/bin/jiff install bashrc
$install_dir/bin/jiff config jiff startup

Then check your login and switch to that window.

EOM
}

return 0 2>/dev/null ||:

set -o errexit
set -o nounset
set -o pipefail

main "$@"
