#!/usr/bin/env bash

main () {
  ! [[ -d "${HOME}/.basher" ]] || exit 0
  pushd "${HOME}" >/dev/null
  git clone --depth=1 git@github.com:basherpm/basher.git .basher
  ! [[ "${SHELL}" == "/bin/bash" ]] || grep -q basher .bashrc || cat <<EOM >> .bashrc

export PATH="\${PATH}:\${HOME}/.basher/bin"
eval "\$(basher init -)"
EOM
  cd .basher/libexec
  sed -i -e 's|${bin_path}:${PATH}|${PATH}:${bin_path}|' basher
  sed -i -e 's|$BASHER_ROOT/cellar/bin:$PATH|$PATH:$BASHER_ROOT/cellar/bin|' -e 's|$BASHER_ROOT/cellar/bin $PATH|$PATH $BASHER_ROOT/cellar/bin|' basher-init
  sed -i -e 's|https://github.com/|git@github.com:|' basher-_clone
  "${HOME}/.basher/bin/basher" install binaryphile/jiff-personal

  if [[ "${SHELL}" == "/bin/bash" ]]; then
    cat <<EOM

You'll want to run "jiff context" to set up platform-specific tasks.

EOM
    exec bash
  fi

! [[ "${SHELL}" == "/usr/bin/fish" ]] || cat <<EOM
Done.

You'll want to run the following command:

set -U fish_user_paths \$fish_user_paths \$HOME/.basher/bin

and restart your shell.

You'll also want to run "jiff context" to set up platform-specific tasks.

EOM
  popd >/dev/null
}

return 2>/dev/null || true
set -o errexit
set -o nounset
set -o pipefail
main "${@}"
