#!/usr/bin/env bash
# Usage: jiff install ranger
# Summary: Install ranger file manager

source stdlib

declare -r RepoUri="bertrand:tmp"
declare -r RangerVer="1.6.1"
declare -r RangerDir="ranger-${RangerVer}"
declare -r Filename="ranger-${RangerVer}.tar.gz"

main () {
  exit_if_is_on_path "ranger"
  install_ranger
}

install_ranger () {
  mkdir -p "${HOME}/tmp"
  cd "${HOME}/tmp"
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  cd "${RangerDir}"
  sudo make install
  cd ..
  sudo rm -rf "${RangerDir}"
  rm "${Filename}"
}

return 0 2>/dev/null || :
strict_mode on
main "$@"
