#!/usr/bin/env bash
# Usage: jiff setup-remote

source concorde.bash
$(feature sremo depth=4)

sremo_main () {
  local host=$1
  local context=$2
  local statements

  $(grab root fromns sremo)
  statements="
    mkdir -pm 700 \"\$HOME\"/.ssh
    echo '$(< $HOME/.ssh/authorized_keys)' >\"\$HOME\"/.ssh/authorized_keys2
    chmod 600 -- \"\$HOME\"/.ssh/authorized_keys2
  "
  put "creating authorized_keys2"
  ssh "$host" "$statements"
  ssh "$host" '! type git >/dev/null 2>&1 && [[ ! -e $HOME/git-2.7.4-static-avwob.tar.gz ]]' && {
    put "copying git"
    scp "$HOME"/misc/git-2.7.4-static-avwob.tar.gz "$host":
  };:
  put "copying setup script"
  scp "$root"/share/setup "$host":
  statements='
    mkdir -pm 700 "$HOME"/dotfiles
    setfacl -m d:g::-,d:o:- "$HOME"/dotfiles
  '
  put "setting dotfiles directory permissions"
  ssh "$host" "$statements"
  put "copying dotfiles"
  rsync -a "$HOME"/dotfiles/ "$host":dotfiles
  put "copying vim configuration"
  rsync -a "$HOME"/.vim/ "$host":.vim
  ssh "$host" "./setup $context"
}

already_running () {
  (( $(pgrep -cf "$1") ))
}

sourced && return
strict_mode on

sremo_main "$@"
