#!/usr/bin/env bash
# Usage: jiff stgit
# Summary: Install stacked git

source stdlib

main () {
  exit_if_is_on_path "stg"
  jiff install git
  install_stgit
}

install_stgit () {
  git clone git@github.com:binaryphile/stgit.git
  cd stgit
  make prefix="${HOME}/.local" all
  make prefix="${HOME}/.local" install
  cd ..
  rm -rf stgit
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${HOME}/tmp" "main" "${@}"
