#!/usr/bin/env bash
# Usage: jiff install vim
# Summary: Install updated vim

source stdlib

declare -r RepoUri="bertrand:tmp"
declare -r Filename="vim-static.tar.gz"
declare -r InstallDir="/opt/app/avwobt4"

main () {
  install_vim
  jiff config vim
}

install_vim () {
  cd "${InstallDir}/lib"
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  # edit the makefile then make install. don't delete the source
  # directory
  rm "${Filename}"
}

return 2>/dev/null || true
strict_mode on
main "$@"
