#!/usr/bin/env bash
# Usage: jiff install-liquidprompt
# Summary: Install bash liquidprompt

source stdlib

declare -r InstallDir="/opt/app/avwobt4"
declare -r RepoUri="bertrand:tmp"
declare -r Filename="liquidprompt.tar.gz"

main () {
  cd "${InstallDir}"
  exit_if_is_file "lib/liquidprompt/liquidprompt"
  install_files
}

install_files () {
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  rm "${Filename}"
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
