#!/usr/bin/env bash
# Usage: jiff mysql

source stdlib
source jifflib

Verb="mysql"

main () {
  run_subtask "${Verb}" "$@"
}

usage () {
  echo "Usage: jiff ${Verb} TASK"
}

return 0 2>/dev/null || :
strict_mode on
main "$@"
