#!/usr/bin/env bash

source concorde.bash

get <<'EOS'
  Usage:  jiff mysql sync [options] <slave> [master]

    Options:
      -n, --dry-run         don't do anything and report sync command
      --master-port=<port>  the port of the master mysql instance
      --slave-port=<port>   the port of the slave mysql instance

    The sync command dumps the master's avwob database to the slave over the
    network.  It does a single-transaction dump with master data.

    If not supplied, master defaults to the current host.

    It employs the backup user credentials on both ends.

    **IMPORTANT:** This is a destructive operation.  It will wipe out the slave's
    copy of the avwob database and replace it with the master's.
EOS
printf -v usage '\n%s\n' "$__"

msync_main () {
  $(grab 'dry_run_flag master_port slave_port' from "$1"); shift
  local slave=${1:-}

  [[ -z $slave ]] && die "$usage"
  stuff 'dry_run_flag master_port slave_port' into ''
  msync "$slave" __
}

msync () {
  local slave=$1; shift
  $(grab 'dry_run_flag master master_port slave_port' from "$@")
  local dump_command
  local load_command

  load_command=( "${mysql_load_command[@]}" -h "$slave"           ${slave_port:+-P $slave_port}   "$database" )
  dump_command=( "${mysql_dump_command[@]}" ${master:+-h $master} ${master_port:+-P $master_port} "$database" )

  (( dry_run_flag )) && { put "${dump_command[*]} | ${load_command[*]}"; return ;}
  "${dump_command[@]}" | "${load_command[@]}"
}

msync_init () {
  defaults=/opt/app/avwobt4/etc/mysql/backup.cnf
  database=avwob_production

  mysql_dump_command=( mysqldump  --defaults-extra-file="$defaults" --single-transaction --master-data  )
  mysql_load_command=( mysql      --defaults-extra-file="$defaults"                                     )
}

msync_init

sourced && return
strict_mode on

get <<'EOS'
  -n  --dry-run     ''            "don't do anything and report sync command"
  ''  --master-port master_port   "the port of the master mysql instance"
  ''  --slave-port  slave_port    "the port of the slave mysql instance"
EOS

$(parse_options __ "$@") || die "$usage" 0
msync_main      __ "$@"  || die "$usage"
