#!/usr/bin/env bash
# Usage: jiff bashrc-install
# Summary: Install bash init files

source stdlib

set_default  "WorkingDir"  "/opt/app/avwobt4"
set_default  "RepoUri"     "bertrand:tmp"
set_default  "Filename"    "bashrc.tar.gz"

main () {
  exit_if_is_file "share/bash/bashrc"
  install_files
}

install_files () {
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  rm "${Filename}"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
