#!/usr/bin/env bash
# Usage: jiff install-git

source stdlib

declare -r InstallDir="/opt/app/avwobt4"
declare -r RepoUri="bertrand:tmp"
declare -r GitVer="2.7.4"
declare -r Filename="git-${GitVer}-static-avwobt4.tar.gz"

main () {
  exit_if_is_on_path "git"
  install_git
}

install_git () {
  cd "${InstallDir}"
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  rm "${Filename}"
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
