#!/usr/bin/env bash
# Usage: jiff ranger-install

source stdlib

WorkingDir="${WorkingDir:-${HOME}/tmp}"
RepoDir="${RepoDir:-bertrand/tmp}"
RangerVer="${RangerVer:-1.6.1}"
RangerDir="${RangerDir:-ranger-${RangerVer}}"
Filename="${Filename:-ranger-${RangerVer}.tar.gz}"

main () {
  install_ranger
}

install_ranger () {
  scp "${RepoDir}/${Filename}" .
  tar xzf "${Filename}"
  cd "${RangerDir}"
  python setup.py install --user
  cd ..
  rm -rf "${RangerDir}"
  rm "${Filename}"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${HOME}/tmp" "main" "${@}"
