#!/usr/bin/env bash
# Usage: jiff vim-install
# Summary: Install personal vim as "myvim"

source stdlib

RepoUri="${RepoUri:-bertrand:tmp}"
Filename="vim-static.tar.gz"
WorkingDir="${WorkingDir:-/opt/app/avwobt4/lib}"

main () {
  install_myvim
  jiff config vim
}

install_myvim () {
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  cd vim
  make install
  cd ..
  rm "${Filename}"
}

return 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
