#!/usr/bin/env bash
# Usage: jiff lnav-install
# Summary: Install the lnav logfile navigator

source stdlib

WorkingDir="${WorkingDir:-${HOME}/tmp}"
InstallDir="${Dir:-/opt/app/avwobt4/bin}"
RepoDir="${RepoDir:-bertrand:tmp}"
LnavVersion="${LnavVersion:-0.8.0}"
LnavDir="lnav-${LnavVersion}"
Filename="${Filename:-${LnavDir}-linux-64bit.tar.gz}"

main () {
  install_lnav
}

install_lnav () {
  scp "${RepoDir}/${Filename}" .
  tar xzf "${Filename}"
  cd "${LnavDir}"
  cp lnav "${InstallDir}"
  cd ..
  rm "${Filename}"
  rm -rf "${LnavDir}"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
