#!/usr/bin/env bash
# Usage: jiff install stgit
# Summary: Install stacked git

source stdlib

declare -r RepoUri="git@github.com:binaryphile/stgit"
declare -r InstallDir="/opt/app/avwobt4"

main () {
  exit_if_is_on_path "stg"
  jiff install git
  install_stgit
}

install_stgit () {
  mkdir -p "${HOME}/tmp"
  cd "${HOME}/tmp"
  git clone "${RepoUri}"
  cd stgit
  make prefix="${InstallDir}" all
  make prefix="${InstallDir}" install
  cd ..
  rm -rf stgit
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
