#!/usr/bin/env bash
# Usage: jiff mysql-show

source stdlib
source jifflib

main () {
  local task

  task="${1:-}"
  shift
  usage_and_exit_if_is_empty "${task}"
  run_and_exit_if_is_jiff_task "${task}-mysql-show" "${@}"
}

usage () {
  echo "Usage: jiff mysql-show TASK"
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
