#!/usr/bin/env bash
# Usage: jiff avwob service

source stdlib

set_default "ServiceUser" "avwob"
set_default "BashEnv" "~${ServiceUser}/.bashrc"

main () {
  sudo -su "${ServiceUser}" BASH_ENV="${BashEnv}" aviewctl "$@"
}

return 0 2>/dev/null || :
strict_mode on
main "$@"
