#!/usr/bin/env bash

source concorde.bash

get <<'EOS'
  Usage:  jiff mysql sync [options] <slave> [master]

    Options:
      -n, --dry-run         don't do anything and report sync command
      --master-port=<port>  the port of the master mysql instance
      --slave-port=<port>   the port of the slave mysql instance

    The sync command dumps the master's avwob database to the slave over the
    network.  It does a single-transaction dump with master data.

    If not supplied, master defaults to the current host.

    It employs the backup user credentials on both ends.

    **IMPORTANT:** This is a destructive operation.  It will wipe out the slave's
    copy of the avwob database and replace it with the master's.
EOS
printf -v _usage '\n%s\n' "$__"

_defaults=/opt/app/avwobt4/etc/mysql/backup.cnf
_database=avwob_production

_mysql_dump_command=( mysqldump  --defaults-extra-file="$_defaults" --single-transaction --master-data  )
_mysql_load_command=( mysql      --defaults-extra-file="$_defaults"                                     )

main () {
  $(grab 'dry_run_flag master_port slave_port' from "$1"); shift
  local slave=${1:-}

  [[ -z $slave ]] && die "$_usage"
  stuff 'dry_run_flag master_port slave_port' into ''
  sync "$slave" __
}

sync () {
  local slave=$1; shift
  $(grab 'dry_run_flag master master_port slave_port' from "$@")
  local dump_command
  local load_command

  load_command=( "${_mysql_load_command[@]}" -h "$slave"           ${slave_port:+-P $slave_port}   "$_database" )
  dump_command=( "${_mysql_dump_command[@]}" ${master:+-h $master} ${master_port:+-P $master_port} "$_database" )

  (( dry_run_flag )) && { put "${dump_command[*]} | ${load_command[*]}"; return ;}
  "${dump_command[@]}" | "${load_command[@]}"
}

sourced && return
strict_mode on

get <<'EOS'
  -n  --dry-run     ''            "don't do anything and report sync command"
  ''  --master-port master_port   "the port of the master mysql instance"
  ''  --slave-port  slave_port    "the port of the slave mysql instance"
EOS

$(parse_options __ "$@")
main __ "$@"
