#!/usr/bin/env bash
# Usage: jiff ag-install

source stdlib

WorkingDir="${WorkingDir:-/opt/app/avwobt4}"
RepoDir="${RepoDir:-bertrand:tmp}"
Filename="${Filename:-ag-static-att.tar.gz}"

main () {
  install_ag
}

install_ag () {
  scp "${RepoDir}/${Filename}" .
  tar xzf "${Filename}"
  rm "${Filename}"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
