#!/usr/bin/env bash
# Usage: jiff stgit
# Summary: Install stacked git

source stdlib

WorkingDir="${WorkingDir:-${HOME}/tmp}"
RepoUri="${RepoUri:-git@github.com:binaryphile/stgit}"
InstallDir="${InstallDir:-/opt/app/avwobt4}"

main () {
  exit_if_is_on_path "stg"
  jiff install git
  install_stgit
}

install_stgit () {
  git clone "${RepoUri}"
  cd stgit
  make prefix="${InstallDir}" all
  make prefix="${InstallDir}" install
  cd ..
  rm -rf stgit
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
