#!/usr/bin/env bash
# Usage: jiff jiff-install

source stdlib

set_default "WorkingDir" "${HOME}"
set_default "InstallDir" "/opt/app/avwobt4"

main () {
  exit_if_is_file "original.bashrc"
  install_files
  success_message
  exec /bin/bash
}

# Let the user make a choice about something and execute code based on
# the answer
# Called like: choose <default (y or n)> <prompt>
# e.g. choose "y" \
#       "Do you want to play a game?" \
# Returns: 0 for yes and 1 for anything else
choose () {
  local default
  local prompt
  local answer

  default="${1}"
  prompt="${2}"
  read -ep "${prompt}" answer
  is_not_empty "${answer}" || answer="${default}"

  case "${answer}" in
    [yY1] ) return 0
      # error check
      ;;
    *     ) return 1
  esac
}

install_files () {
  choose "y" "This will replace your bashrc and bash_profile...Continue? (Y/n) " || exit 1
  is_not_file ".bashrc" || mv .bashrc original.bashrc
  is_not_file ".bash_profile" || mv .bash_profile original.bash_profile
  cp "${InstallDir}/share/bash/bashrc" .bashrc
  cp "${InstallDir}/share/bash/bash_profile" .bash_profile
}

success_message () {
  cat <<EOM

jiff has been installed and your files are backed up as
"original.bashrc" and "original.bash_profile".

EOM
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
