#!/usr/bin/env bash
# Usage: jiff install-bashrc
# Summary: Install bash init files

source stdlib

declare -r InstallDir="/opt/app/avwobt4"
declare -r RepoUri="bertrand:tmp"
declare -r Filename="bashrc.tar.gz"

main () {
  cd "${InstallDir}"
  exit_if_is_file "share/bash/bashrc"
  install_files
}

install_files () {
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  rm "${Filename}"
}

return 0 2>/dev/null || :
strict_mode on
main "$@"
