#!/usr/bin/env bash
# Usage: jiff avwob show

source stdlib

main () {
  is_match "${1}" "process" || exit 1
  if pgrep -f jboss | xargs ps -fp 2>/dev/null; then
    echo
    echo "avwob jboss instance is running"
  else
    echo "avwob jboss instance is not running"
  fi
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
