#!/usr/bin/env bash
# Usage: jiff task-add

source "${_JIFF_ROOT}/../../binaryphile/jiff-core/libexec/jiff-task-add"

set_taskdir () {
  case "${1}" in
    "role" )
      echo "../role/current"
      ;;
    "default" )
      echo ""
      ;;
    "core" )
      echo "../../../binaryphile/jiff-core/libexec"
      ;;
    * )
      echo "../context/current"
  esac
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
cd "${_JIFF_ROOT}/../jiff/libexec"
make_symlink "jiff-${2}" ../../../binaryphile/libexec/jiff-${2}"
git add "jiff-${2}"
git commit -m "automated commit"
git push
cd "${_JIFF_ROOT}"
git rm --force "libexec/jiff-${2}"
git fetch upstream
git rebase upstream/master
git push --force
