#!/usr/bin/env bash
# Usage: jiff personal-push

source std.sh

main() {
  jiff install git
  std::push_dir "${HOME}/binaryphile/jiff-personal"
  git fetch upstream
  git rebase upstream/master
  git push -f
  std::pop_dir
}

return 0 2>/dev/null || :
std::strict_mode on
main "$@"
