#!/usr/bin/env bash
# Usage: jiff task add|edit|publish|remove|show taskname
# Summary: Manage jiff tasks

source "${_JIFF_ROOT}/../../binaryphile/jiff-core/libexec/jiff-task"

set_taskdir() {
  case "$1" in
    "role" )
      printf "%s/role/current" "${_JIFF_ROOT}"
      ;;
    "default" )
      printf "%s/libexec" "${_JIFF_ROOT}"
      ;;
    "core" )
      printf "%s/../../binaryphile/jiff-core/libexec" "${_JIFF_ROOT}"
      ;;
    * )
      printf "%s/context/current" "${_JIFF_ROOT}"
  esac
}

return 2>/dev/null || :
std::strict_mode on
main "$@"
