#!/usr/bin/env bash
# Usage: jiff git
# Summary: Install git 2

source stdlib

read -d "" -a Prereqs <<EOM || true
gcc
curl-devel
expat-devel
gettext-devel
openssl-devel
perl-devel
zlib-devel
perl-Error
EOM
declare -r Prereqs

main () {
  exit_if_is_on_path "git"
  install_prereqs
  install_git
}

install_git () {
  mkdir -p "${HOME}/tmp"
  cd "${HOME}/tmp"
  wget https://downloads.accns.com/git/git-2.7.0.tar.gz
  tar xzf git-2.7.0.tar.gz
  cd git-2.7.0
  make configure
  ./configure --prefix=/usr
  make all
  sudo make install
  cd ..
  rm -rf git-2.7.0
  rm git-2.7.0.tar.gz
}

install_prereqs () {
  local prereq

  for prereq in "${Prereqs[@]}"; do
    jiff install "${prereq}"
  done
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
