#!/usr/bin/env bash
# Usage: jiff mysql-enterprise-install

source stdlib
source distrolib

read -d "" -a Packages <<EOM || true
mysql-connector-python-commercial-2.1.3-1.1.el6.x86_64.rpm
MySQL-server-advanced-5.6.24-1.el6.x86_64.rpm
MySQL-client-advanced-5.6.24-1.el6.x86_64.rpm
mysql-utilities-commercial-1.5.6-1.el6.noarch.rpm
mysql-utilities-commercial-extra-1.5.6-1.el6.noarch.rpm
meb-4.0.0-el6.x86_64.rpm
EOM

read -d "" -a Prereqs <<EOM || true
libaio
numactl
EOM

main () {
  jiff slash-git
  uninstall_package "mysql-libs"
  install_prereqs
  install_packages
  move_my_cnf
  start_service "mysql"
  /usr/bin/mysql_secure_installation
  create_extra_defaults_file
}

create_extra_defaults_file () {
  mkdir -p "${HOME}/.config/mysql"
  cd "${HOME}/.config/mysql"
  chmod 770 .
  cat <<EOM >> my.cnf
[client]
user=root
password=$(sudo cat /root/.mysql_secret | awk -F": " '{ print $2 }')
EOM
  chmod 660 my.cnf
}

install_packages () {
  local package

  for package in "${Packages[@]}"; do
    is_not_file "${package}" || continue
    wget "https://downloads.accns.com/mysql/${package}"
    install_local_package "${package}" || true
  done
  for package in "${Packages[@]}"; do
    rm "${package}"
  done
}

install_prereqs () {
  local prereq

  for prereq in "${Prereqs[@]}"; do
    install_package "${prereq}"
  done
}

move_my_cnf () {
  cd /usr
  sudo cp my.cnf /etc/mysql
  sudo rm my.cnf
  cd /etc/mysql
  git add -f my.cnf
  git commit -m "my.cnf"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${HOME}/tmp" "main" "${@}"
