#!/usr/bin/env bash
# Usage: jiff basher [admin group (default: prodadm)]
# Summary: Set up basher package manager

source stdlib

read -d "" BashText <<EOM
if [[ "\$(id -u)" -gt 199 ]] && [[ "\$(id -u)" -ne 10000 ]] && [[ -z "\${BASHER_ROOT}" ]]; then
  export BASHER_ROOT=/opt/basher
  export PATH="\${PATH}:/opt/basher/bin"
  eval "\$(basher init -)"
fi
EOM

main () {
  exit_if_is_in_path basher
  jiff slash-git
  install_basher
}

install_basher () {
  cd /etc/profile.d
  echo "${BashText}" | sudo tee basher.sh
  git add --force basher.sh
  git commit --message "basher"
  cd /opt
  make_group_dir basher
  git clone git://github.com/basherpm/basher
  cd basher/libexec
  substitute_in_file basher '${bin_path}:${PATH}' '${PATH}:${bin_path}'
  substitute_in_file basher-init '$BASHER_ROOT/cellar/bin:$PATH' '$PATH:$BASHER_ROOT/cellar/bin'
  substitute_in_file basher-init '$BASHER_ROOT/cellar/bin $PATH' '$PATH $BASHER_ROOT/cellar/bin'
  substitute_in_file basher-_clone 'https://github.com/' 'git@github.com:'
}

return 0 2>/dev/null || :
strict_mode on
main "$@"
