#!/usr/bin/env bash
# Usage: jiff git
# Summary: Install git 2

source stdlib

declare -r RepoUri=https://downloads.accns.com/git
declare -r GitVersion=2.7.4
declare -r GitDir="git-${GitVersion}"
declare -r Filename="${GitDir}.tar.gz"

read -d "" -a Prereqs <<EOM || true
gcc
curl-devel
expat-devel
gettext-devel
openssl-devel
perl-devel
zlib-devel
perl-Error
EOM
declare -r Prereqs

main () {
  exit_if_is_on_path "git"
  install_prereqs
  install_git
}

install_git () {
  mkdir -p "${HOME}/tmp"
  push_dir "${HOME}/tmp"
  scp "${RepoUri}/${Filename}" .
  tar xzf "${Filename}"
  cd "${GitDir}"
  make configure
  ./configure --prefix=/usr
  make all
  sudo make install
  cd ..
  rm -rf "${GitDir}"
  rm "${Filename}"
  pop_dir
}

install_prereqs () {
  local prereq

  for prereq in "${Prereqs[@]}"; do
    jiff install "${prereq}"
  done
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
